PROGRAM=sms
COMPILER=c99
OPTIONS=-Wall -Wextra -pedantic -std=c99 -l sqlite3
COMPILE=$(COMPILER) $(OPTIONS)

PROGRAM: sms.c
	$(COMPILE) sms.c -o sms.out
#PROGRAM: test.c
#	$(COMPILE) test.c -o test.out
